# fly.toml app configuration file generated for subreddit-ingestion on 2023-09-04T16:45:38-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "subreddit-ingestion"
primary_region = "dfw"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  processes = ["app"]
